{% set name = "adwaita-icon-theme" %}
{% set version = "48.0" %}
{% set major_version = version.split('.')[0] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ major_version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 847068888650d9673115be6dbf2bfdc31a46aebc528a6a9db4420e60e656b8d4

build:
  number: 0
  noarch: generic
  string: "unix_{{ PKG_BUILDNUM }}"  # [unix]
  string: "win_{{ PKG_BUILDNUM }}"  # [win]
  merge_build_host: false

requirements:
  build:
    # gtk needed for building icon cache, build OK because cache file is platform-independent
    - gtk3
    - meson
    - ninja
    - python
  host:
    # explicitly empty
  run:
    - __unix  # [unix]
    - __win  # [win]
    - hicolor-icon-theme
    # librsvg needed at runtime for libpixbufloader-svg.so so svgs can be rendered
    - librsvg

test:
  commands:
    # test that a representative set of files get installed
    - test -f $PREFIX/share/icons/Adwaita/icon-theme.cache  # [unix]
    - test -f $PREFIX/share/icons/Adwaita/index.theme  # [unix]
    - test -f $PREFIX/share/icons/Adwaita/16x16/devices/audio-headphones.png  # [unix]
    - test -f $PREFIX/share/icons/Adwaita/cursors/cross  # [unix]
    - test -f $PREFIX/share/icons/Adwaita/cursors/default  # [unix]
    - test -f $PREFIX/share/icons/Adwaita/scalable/devices/computer.svg  # [unix]
    - if not exist %PREFIX%\Library\share\icons\Adwaita\icon-theme.cache exit 1  # [win]
    - if not exist %PREFIX%\Library\share\icons\Adwaita\index.theme exit 1  # [win]
    - if not exist %PREFIX%\Library\share\icons\Adwaita\16x16\devices\audio-headphones.png  exit 1  # [win]
    - if not exist %PREFIX%\Library\share\icons\Adwaita\cursors\crosshair.cur exit 1  # [win]
    - if not exist %PREFIX%\Library\share\icons\Adwaita\cursors\default.cur exit 1  # [win]
    - if not exist %PREFIX%\Library\share\icons\Adwaita\scalable\devices\computer.svg exit 1  # [win]

about:
  home: https://developer.gnome.org
  license: LGPL-3.0-or-later OR CC-BY-SA-3.0
  license_family: LGPL
  license_file: COPYING
  summary: The default icon theme used by the GNOME desktop
  description: |
    This package contains the default icon theme used by the GNOME desktop.
    The icons are used in many of the official GNOME applications like eog,
    Evince, system monitor, and many more.
  dev_url: https://gitlab.gnome.org/GNOME/adwaita-icon-theme

extra:
  recipe-maintainers:
    - ryanvolz
    - stuarteberg
    - tschoonj
